export const UPDATE_AUTH = 'UPDATE_AUTH'
export const FETCH_REQUEST_AUTH = 'FETCH_REQUEST_AUTH'
export const FETCH_ERROR_AUTH = 'FETCH_ERROR_AUTH'
export const LOGOUT = 'LOGOUT'
export const TOGGLE_USER_MODAL = 'TOGGLE_USER_MODAL'
export const TOGGLE_AUTH_FORM_MODAL = 'TOGGLE_AUTH_FORM_MODAL'

