export const ONCHANGE_FILTERS = 'ONCHANGE_FILTERS'
export const ONCHANGE_PAGE = 'ONCHANGE_PAGE'
export const RESET_FILTERS = 'RESET_FILTERS'
export const ONCHANGE_TOTAL_PAGES = 'ONCHANGE_TOTAL_PAGES'
